server:
  port: 3002
  servlet:
    context-path: /pancardservice

spring:
  application:
    name: Pancard-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pancarddetails
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      #  - health
  endpoint:
    health:
      show-details: always
      
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/